# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven and Allure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      browserName:
        description: 'Browser type'
        required: false
        type: string
        default: 'chrome'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      id: build
      run: mvn clean -f DemoAutomationProject/pom.xml
    
    - name: Run tests
      if: steps.build.outcome == 'success'
      run: mvn -DbrowserName=${{ inputs.browserName || 'CHROME' }} verify DemoAutomationProject/pom.xml
    
    - name: Get Allure history
      uses: actions/checkout@v3
      if: steps.build.outcome == 'success'
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    
    - name: Allure Report action
      uses: simple-elf/allure-report-action@master
      if: steps.build.outcome == 'success'
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
    
    - name: Deploy report to Github Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v4
      with:
        target_branch: gh-pages
        build_dir: allure-history
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
